# Generated by Django 2.2.6 on 2019-11-15 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('charity_contact_name', models.CharField(max_length=64)),
                ('charity_contact_email', models.CharField(max_length=128)),
                ('charity_contact_phone', models.CharField(max_length=64)),
                ('charity_category', models.CharField(max_length=128)),
                ('charity_donators', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
                ('category_charities', models.ManyToManyField(to='api.Charity')),
                ('category_donators', models.ManyToManyField(to='api.Profile')),
            ],
        ),
    ]
