# Generated by Django 2.1.1 on 2019-11-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('charity_contact_name', models.CharField(max_length=64)),
                ('charity_contact_email', models.CharField(max_length=128)),
                ('charity_contact_phone', models.CharField(max_length=64)),
                ('charity_category', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='charities',
            field=models.ManyToManyField(to='api.Charity'),
        ),
    ]
