# Generated by Django 2.1.1 on 2019-11-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191118_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Animal Rights', 'Animal Rights'), ('Other', 'Other')], default='Other', max_length=128)),
                ('description', models.TextField(default='')),
                ('category_charities', models.ManyToManyField(blank=True, to='api.Charity')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='charities',
            field=models.ManyToManyField(blank=True, to='api.Charity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
