# Generated by Django 2.1.1 on 2019-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191125_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_donator',
            field=models.IntegerField(default=0),
        ),
    ]
